services:
    monolog.formatter.session_request:
        class: Monolog\Formatter\LineFormatter
        arguments:
            - "[%%datetime%%] [%%extra.user%%] %%channel%%.%%level_name%%: %%message%%\n"

    monolog.processor.psr_log_message_processor:
        class: Monolog\Processor\PsrLogMessageProcessor
        tags:
            - { name: monolog.processor, handler: console }
